name: CI

on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main
jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-dev.txt

    - name: Run Linter
      run: |
        pip install pylint==4.0.2
        pylint tests/ src/pynetevents/

    - name: Ensure black formatting
      run: |
        pip install black==25.9.0
        black --check tests/ src/pynetevents/

    - name: Install editable package
      run: |
        python -m pip install -e .

    - name: Run Unit Tests and generate coverage report
      run: |
        pytest

    - name: Archive code coverage html report
      uses: actions/upload-artifact@v4
      with:
        name: code-coverage-report
        path: coverage/html/
    
    - name: Archive code coverage xml report
      uses: actions/upload-artifact@v4
      with:
        name: code-coverage-xml
        path: coverage/coverage.xml
    
    - name: Upload coverage reports to Codecov
      if: ${{ vars.UPLOAD_COVERAGE == 'true' && github.event_name == 'push' && github.ref == 'refs/heads/master' }}
      uses: codecov/codecov-action@v5
      with:
        files: coverage/coverage.xml
        token: ${{ secrets.CODECOV_TOKEN }}